<div id="game-board">
    <button class="help-btn" onclick="GameBridge.speak('Look at the target color. Click the bottles to mix that color in the big beaker.')">🔊 Help</button>

    <!-- The "Customer Order" or Target -->
    <div id="target-display">
        <div class="target-label">MAKE THIS:</div>
        <div id="target-swatch" class="swatch pulse"></div>
        <div id="target-name">Purple</div>
    </div>

    <!-- The Mixing Station -->
    <div id="mixing-station">
        <div id="main-beaker">
            <div id="liquid"></div>
            <div class="bubbles">
                <span></span><span></span><span></span>
            </div>
        </div>
    </div>

    <!-- Ingredient Shelf -->
    <div id="shelf">
        <!-- Generated by JS -->
    </div>

    <!-- Controls -->
    <div id="controls">
        <button id="btn-reset" onclick="emptyBeaker()">Empty 🗑️</button>
        <button id="btn-mix" onclick="checkMix()">Mix It! 🧪</button>
    </div>

    <div id="message"></div>
</div>